name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: yarn install, and lint
        working-directory: ./
        run: |
          yarn install --frozen-lockfile
          yarn lint
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Deploy
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/godingeo:latest
          build-args: |
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
            DATABASE_PORT=${{ sercrets.DATABASE_PORT }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            JWT_KEY=${{ secrets.JWT_KEY }}
            BUCKETNAME=${{ secrets.BUCKETNAME }}
            ACCESSKEY=${{ secrets.ACCESSKEY }}
            SECRETACCESSKEY=${{ secrets.SECRETACCESSKEY }}
